AWSTemplateFormatVersion: 2010-09-09
Resources:
  ECSCluster:
    Type: 'AWS::ECS::Cluster'
    Properties:
      ClusterName: takehomecluster
  taskdefinition:
    Type: 'AWS::ECS::TaskDefinition'

  ECSService:
    Type: 'AWS::ECS::Service'
    Properties:
      ServiceName: takehome-service
      Cluster: !Ref ECSCluster
      DesiredCount: 1
      LaunchType: FARGATE
      TaskDefinition: !Ref taskdefinition
