AWSTemplateFormatVersion: "2010-09-09"
Resources:
  LoadBalancerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
        - 
          TargetGroupArn: !Ref TargetGroup
          Type: forward
      Conditions:
        - 
          Field: path-pattern
          Values: takehome
      ListenerArn: arn:aws:elasticloadbalancing:us-east-1:519927740453:listener/app/takehome-loadbalancer/6f5473243418b636/a74fee066e5d8fd8
      Priority: 1
  Service:
    Type: AWS::ECS::Service
    DependsOn: LoadBalancerRule
    Properties:
      Cluster: takehomecluster
      DesiredCount: 1
      HealthCheckGracePeriodSeconds: 400
      LaunchType: FARGATE
      LoadBalancers:
        - 
          ContainerName: takehome-container
          ContainerPort: 80
          TargetGroupArn: !Ref TargetGroup
      NetworkConfiguration:
        AwsVpcConfiguration:
          Subnets: subnet-0450e5a517afb0696
          SecurityGroups: sg-042100be4fb5c1495
      ServiceName: takehome-service
      TaskDefinition: !Ref TaskDefinition
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        - 
          Cpu: 256
          Image: !Ref Image
          Memory: 512
          Name: takehome-container
          PortMappings:
            - 
              ContainerPort: 80
              Protocol: tcp
            -
              Cpu: 512
      Cpu: 1024
      ExecutionRoleArn: arn:aws:iam::519927740453:role/takehome
      Memory: 2048
      NetworkMode: awsvpc
      TaskRoleArn: arn:aws:iam::519927740453:role/takehome
